spring:
  application:
    name: bus_service
  datasource:
    url: jdbc:h2:mem:bus-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
