server:
  port: 8761

spring:
  application:
    name: eureka_server
  config:
    import: optional:configserver:http://localhost:9101

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
