spring:
  application:
    name: student_service
  config:

  datasource:
    url: jdbc:h2:mem:student-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

server:

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
